name: edge_library_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  riverpod: ^2.4.0
  edge_library_common:
    path: ../edge_library_api/packages/edge_library_common
  flextras: ^1.0.0
  flex_color_scheme: ^7.3.1
  go_router: ^10.1.2
  loggy: ^2.0.3
  logging: ^1.2.0
  collection: ^1.17.2
  passage_flutter: ^0.1.0
  result_dart: ^1.1.0
  gap: ^3.0.1
  equatable: ^2.0.5
  wolt_modal_sheet: ^0.1.2
  uno: ^1.1.9
  intl: ^0.18.1
  option_result: ^3.1.2
  envied: ^0.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  envied_generator: ^0.3.0+3
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
