name: edge_library_common
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.1.0

dependencies:
  dart_mappable: ^3.1.3
  result_dart: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  dart_mappable_builder: ^3.2.0
  lints: ^2.0.0
  test: ^1.21.0
