name: edge_library_data
description: A sample command-line application.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  supabase: ^1.11.1
  edge_library_common:
    path: ../edge_library_common
  dart_jsonwebtoken: ^2.11.0
  result_dart: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^2.0.0
  test: ^1.21.0
